name: Submit Application

on:
    workflow_dispatch: # manual trigger (safe + expected)

jobs:
    submit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.11"

            - name: Run submission script
              env:
                  REPO_NAME: ${{ github.repository }}
                  ACTION_RUN_LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

                  NAME: ${{ secrets.NAME }}
                  EMAIL: ${{ secrets.EMAIL }}
                  RESUME_LINK: ${{ secrets.RESUME_LINK }}

                  SUBMISSION_URL: ${{ secrets.SUBMISSION_URL }}
                  SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}

              run: python main.py
